// js/story.js - Pusat Teks Cerita Scrapbook
const STORY_CONTENT = [
    { type: "section_start", id: "sec-1" },
    { type: "decoration", class: "doodle-date", text: "06 Aug 26" },
    { type: "decoration", class: "vintage-postage-stamp", style: "top: -10px; right: 10px; transform: rotate(8deg);", text: "<div class='stamp-inner'>💌</div>" },
    { type: "title", text: "Hari yang selalu ingin aku rayakan" },
    { type: "paragraph", text: "Selamat ulang tahun ya, Ciya." },
    { type: "paragraph", text: "Akhirnya hari ini datang juga. Hari yang dari beberapa minggu lalu udah aku tunggu-tunggu. Hari di mana perempuan yang paling aku sayang genap berusia 17 tahun." },
    { type: "paragraph", text: "Jujur, aku seneng banget bisa ada di hari ulang tahun kamu. Walaupun mungkin aku belum bisa ngerayain bareng kamu sepuas yang aku mau, atau belum bisa ngasih semua hal yang aku pengen kasih, tapi aku tetap bersyukur karena masih dikasih kesempatan buat jadi bagian dari hari spesial kamu tahun ini." },
    { type: "paragraph", text: "Dari jauh-jauh hari aku udah kepikiran, \"Aku harus ngasih apa ya buat Ciya?\"" },
    { type: "paragraph", text: "Aku muter otak berkali-kali. Aku nyari banyak ide. Sampai akhirnya aku sadar kalau yang paling pengen aku kasih ke kamu bukan cuma hadiah yang bisa dipegang, tapi sesuatu yang bisa kamu buka lagi kapan pun kalau suatu hari nanti kamu lagi kangen, lagi sedih, atau cuma pengen nginget hari ini." },
    { type: "paragraph", text: "Makanya aku memutuskan buat bikin ini." },
    { type: "paragraph", text: "Mungkin kalau kamu sadar, beberapa hari terakhir aku sering banget slow response. Kadang balas chat lama, kadang lagi ngoding terus tiba-tiba ngilang. Aku tahu itu pasti bikin kamu kesel, bahkan mungkin sempat ngerasa aku kurang perhatian sama kamu." },
    { type: "paragraph", text: "Maaf ya." },
    { type: "paragraph", text: "Aku benar-benar minta maaf soal itu." },
    { type: "paragraph", text: "Bukan karena aku bosen ngobrol sama kamu, bukan karena rasa sayangku berkurang, apalagi karena aku udah nggak peduli. Justru selama beberapa hari terakhir aku lagi sibuk nyiapin semua ini buat kamu. Aku pengen pas hari ulang tahun kamu tiba, aku bisa ngasih sesuatu yang beda dari biasanya. Sesuatu yang benar-benar dibuat khusus buat kamu, bukan tinggal beli lalu dibungkus." },
    { type: "paragraph", text: "Jujur aja, bikin aplikasi ini nggak semudah yang aku kira. Ada banyak bagian yang harus aku ulang lagi, ada tampilan yang sempat berantakan, ada fitur yang tiba-tiba rusak, bahkan ada beberapa kali aku ngerasa capek sendiri karena hasilnya nggak sesuai sama yang aku bayangin." },
    { type: "paragraph", text: "Tapi setiap kali aku kepikiran kalau nanti yang bakal buka aplikasi ini adalah kamu, aku milih lanjut lagi." },
    { type: "paragraph", text: "Aku pengen semuanya kelihatan sebagus mungkin. Aku pengen setiap halaman yang kamu buka terasa spesial. Aku pengen setiap foto, setiap video, setiap lagu, bahkan setiap kata yang nanti kamu baca bisa bikin kamu ngerasa kalau semua ini memang dibuat cuma buat satu orang." },
    { type: "paragraph", text: "Buat kamu." },
    { type: "paragraph", text: "Aku nggak tahu apakah ini bakal jadi hadiah ulang tahun terbaik yang pernah kamu terima atau bukan. Tapi satu hal yang aku tahu, belum pernah ada hadiah yang aku siapin selama ini dengan waktu, tenaga, dan perasaan sebanyak ini." },
    { type: "paragraph", text: "Jadi sebelum kita lanjut ke halaman berikutnya, aku cuma mau bilang..." },
    { type: "paragraph", text: "Selamat ulang tahun ya, Ciya." },
    { type: "paragraph", text: "Terima kasih karena tanpa sadar kamu udah bikin hidup aku jauh lebih berwarna dari sebelumnya. Terima kasih karena udah hadir, udah bertahan, dan udah mau nerima aku dengan segala kurang lebihnya." },
    { type: "paragraph", text: "Semoga setelah ini kamu menikmati semua cerita kecil yang udah aku simpan di dalam aplikasi ini. Karena setiap hal yang bakal kamu lihat setelah ini adalah bagian dari perjalanan kita, dan semuanya punya cerita yang pengen aku bagi sama kamu." },
    { type: "quote", text: "\"Terkadang hal paling sederhana menjadi memori paling indah.\"" },
    { type: "decoration", class: "doodle-paint d-sun", style: "top: 25%; left: -15px;" },
    { type: "decoration", class: "fabric-ribbon", style: "bottom: 10px; left: 20px;", text: "MEMORIES" },
    { type: "photo", id: "media-foto-1", align: "protrude-right" },
    { type: "section_end" },
    { type: "divider" },

    { type: "section_start", id: "sec-2" },
    { type: "decoration", class: "coffee-stain", style: "top: -20px; right: 10px;" },
    { type: "title", text: "Semua berawal dari sini" },
    { type: "paragraph", text: "Kalau dipikir-pikir lucu juga ya..." },
    { type: "paragraph", text: "Siapa sangka, dari sekian banyak orang di dunia ini, aku malah dipertemukan sama kamu lewat sebuah aplikasi dating." },
    { type: "paragraph", text: "Waktu itu aku sama sekali nggak kepikiran kalau orang yang awalnya cuma aku sapa ternyata bakal jadi seseorang yang sekarang begitu berarti buat aku." },
    { type: "paragraph", text: "Tanggal 9 Mei 2026 jadi awal dari semuanya." },
    { type: "paragraph", text: "Sampai akhirnya waktu terus berjalan, kita mulai ketemu, mulai bikin kenangan, mulai punya cerita yang kalau diingat sekarang rasanya bikin senyum sendiri." },
    { type: "paragraph", text: "Jujur, aku nggak pernah nyangka kalau pertemuan yang sesederhana itu bisa membawa kita sampai sejauh ini." },
    { type: "paragraph", text: "Mungkin buat orang lain ini cuma hubungan yang baru berjalan beberapa bulan." },
    { type: "paragraph", text: "Tapi buat aku, waktu yang kita lewatin selama ini udah cukup buat bikin aku sadar kalau kehadiran kamu membawa banyak warna baru dalam hidup aku." },
    { type: "decoration", class: "doodle-paint d-cloud", style: "top: -5px; left: -10px;" },
    { type: "decoration", class: "doodle-paint d-flower", style: "bottom: 20%; right: -15px;" },
    { type: "video", id: "media-video-1", align: "protrude-left" },
    { type: "paragraph", text: "Ada kalanya kita hanya diam, tapi entah kenapa suasananya tidak pernah terasa kosong." },
    { type: "decoration", class: "vintage-label-tag", style: "margin-bottom: 15px;", text: "special moment" },
    { type: "stacked_photos", topId: "media-foto-3", bottomId: "media-foto-2" },
    { type: "section_end" },
    { type: "divider" },

    { type: "section_start", id: "sec-3" },
    { type: "title", text: "Potongan Kenangan" },
    { type: "decoration", class: "ink-smudge", style: "top: 10px; left: 40%;" },
    { type: "paragraph", text: "Setiap foto di bawah ini punya ceritanya sendiri." },
    { type: "paragraph", text: "Mungkin buat orang lain ini cuma gambar biasa." },
    { type: "paragraph", text: "Tapi buat aku, setiap senyum, setiap tatapan, setiap momen yang berhasil kita abadikan selalu punya alasan untuk diingat." },    
    { type: "paragraph", text: "Terima kasih ya... karena tanpa sadar, kamu udah jadi bagian dari banyak kenangan indah yang aku punya. 🤍" },    
    { type: "decoration", class: "fabric-ribbon", style: "top: 0; left: 10px; transform: rotate(-5deg);", text: "OUR JOURNEY" },
    { type: "photo", id: "media-foto-4", align: "protrude-right" },
    { type: "photo", id: "media-foto-5", align: "pos-left", decor: "thumbtack" },
    { type: "decoration", class: "doodle-paint d-leaf", style: "bottom: 10%; right: -10px;" },
    { type: "photo", id: "media-foto-6", align: "protrude-right" },
    { type: "section_end" },
    { type: "divider" },

    { type: "section_start", id: "sec-4" },
    { type: "title", text: "Kenangan yang kembali hidup" },
    { type: "paragraph", text: "Kalau foto bisa menghentikan waktu..." },
    { type: "paragraph", text: "Mungkin video adalah cara kita menghidupkannya kembali." },
    { type: "paragraph", text: "Beberapa detik yang berhasil kita rekam ini mungkin terlihat sederhana." },
    { type: "paragraph", text: "Tapi buat aku, setiap detiknya selalu punya cerita. 🤍" },
    { type: "video", id: "media-video-3", align: "pos-right" },
    { type: "decoration", class: "vintage-postage-stamp", style: "bottom: 5px; left: 10px; transform: rotate(-12deg);", text: "<div class='stamp-inner'>✨</div>" },
    { type: "photo", id: "media-foto-7", align: "pos-left" },
    { type: "section_end" },
    { type: "divider" },

    { type: "section_start", id: "sec-5" },
    { type: "decoration", class: "deco-dried-flower", style: "top: 10px; right: -10px;", text: "🥀" },
    { type: "title", text: "Hal yang belum pernah aku ucapkan" },
    { type: "paragraph", text: "ciya..." },
  { type: "paragraph", text: "Ada beberapa hal yang selama ini pengen banget aku bilang ke kamu, tapi entah kenapa setiap ada kesempatan, aku malah nggak pernah bisa nyampeinnya dengan baik." },
  { type: "paragraph", text: "Pertama, aku mau minta maaf." },
  { type: "paragraph", text: "Maaf kalau selama ini aku masih sering bikin kamu nunggu. Maaf kalau aku belum bisa ngasih perhatian sebanyak yang kamu harapkan. Aku tahu, perhatian itu salah satu hal yang paling kamu butuhin, tapi justru di situ aku masih sering kurang." },
  { type: "paragraph", text: "Aku juga minta maaf karena pernah bikin kamu nangis gara-gara aku cerita tentang masa lalu. Sampai sekarang, kalau inget itu, aku masih nyesel. Harusnya aku lebih mikirin perasaan kamu daripada sibuk cerita tentang sesuatu yang udah selesai." },
  { type: "paragraph", text: "Dan satu lagi yang mungkin belum pernah aku bilang..." },
  { type: "paragraph", text: "Terima kasih ya, karena sampai hari ini kamu masih mau bertahan, masih mau percaya sama aku, dan masih mau jalan bareng sama aku." },
  { type: "paragraph", text: "Aku janji akan terus belajar jadi laki-laki yang lebih baik. Mungkin aku nggak bisa berubah dalam semalam, tapi aku nggak akan berhenti berusaha, karena kamu pantas mendapatkan versi terbaik dari diriku. 🤍" },
    { type: "decoration", class: "vintage-label-tag", text: "best wishes" },
    { type: "photo", id: "media-foto-8", align: "protrude-right" },
    { type: "video", id: "media-video-4", align: "pos-left" },
    { type: "section_end" },
    { type: "divider" },

    { type: "section_start", id: "sec-6" },
    { type: "title", text: "Harapan dan Doa" },
    { type: "paragraph", text: "Semoga" },
  { type: "paragraph", text: "Kalau ada satu hal yang paling sering aku lakuin buat kamu selain sayang sama kamu, mungkin itu adalah berdoa." },
  { type: "paragraph", text: "Aku nggak pernah tahu apa yang akan terjadi besok, bulan depan, atau beberapa tahun lagi. Tapi aku selalu berharap, semoga Tuhan selalu menjaga perempuan yang sekarang lagi baca surat ini." },
  { type: "paragraph", text: "Semoga kamu selalu diberi kesehatan, bukan cuma tubuh yang sehat, tapi juga hati yang tenang dan pikiran yang nggak mudah lelah menghadapi dunia." },
  { type: "paragraph", text: "Semoga kamu selalu dikelilingi orang-orang baik yang tulus sayang sama kamu, yang menghargai kamu, dan yang selalu ngelihat betapa berharganya diri kamu." },
  { type: "paragraph", text: "Semoga semua mimpi yang sekarang lagi kamu kejar satu per satu bisa tercapai. Semoga nanti kamu lulus sekolah dengan hasil yang bikin kamu bangga, bisa kuliah di tempat yang kamu inginkan, menemukan pekerjaan yang kamu sukai, dan menjalani hidup yang selalu kamu impikan." },
  { type: "paragraph", text: "Aku juga berdoa semoga kamu nggak pernah kehilangan senyum yang selama ini bikin aku jatuh hati. Tetap jadi Ciya yang manja, yang cerewet, yang penyayang, yang kadang ngambekan, karena justru hal-hal kecil itu yang bikin kamu jadi diri kamu sendiri." },
  { type: "paragraph", text: "Dan kalau suatu hari nanti hidup lagi berat, semoga Tuhan selalu kasih kamu orang-orang yang bisa jadi tempat pulang. Kalau aku masih ada di sampingmu saat itu, izinin aku jadi salah satunya." },
  { type: "paragraph", text: "Aku juga punya doa yang mungkin sedikit egois." },
  { type: "paragraph", text: "Aku berharap semoga kita masih dipertemukan di ulang tahunmu yang ke-18, ke-19, ke-20, sampai nanti suatu saat aku bisa ngucapin ”selamat ulang tahun” sambil duduk di samping kamu, bukan lagi lewat layar." },
  { type: "paragraph", text: "Aku berharap bisa nemenin kamu lulus sekolah." },
  { type: "paragraph", text: "Nemenin kamu masuk kuliah." },
  { type: "paragraph", text: "Nemenin kamu mulai bekerja." },
  { type: "paragraph", text: "Sampai nanti, di waktu yang tepat, aku bisa datang ke rumahmu, bertemu kedua orang tuamu, memperkenalkan diri dengan baik, dan meminta izin untuk menjaga perempuan yang selama ini begitu aku sayangi." },
  { type: "paragraph", text: "Kalau Tuhan mengizinkan semua itu terjadi, mungkin itu akan jadi doa paling indah yang pernah dikabulkan dalam hidupku." },
  { type: "paragraph", text: "Terakhir..." },
  { type: "paragraph", text: "Terima kasih ya, Ciya." },
  { type: "paragraph", text: "Terima kasih karena tanpa sadar kamu udah jadi salah satu alasan kenapa aku selalu semangat menjalani hari." },
  { type: "paragraph", text: "Semoga Tuhan selalu menjaga setiap langkahmu." },
  { type: "paragraph", text: "Dan semoga, kalau memang kita ditakdirkan untuk berjalan bersama, Tuhan menjaga kita sampai benar-benar bisa pulang ke tujuan yang sama. 🤍" },
  
    { type: "decoration", class: "doodle-paint d-sun", style: "top: 40%; left: -20px;" },
    { type: "video", id: "media-video-5", align: "protrude-right" },
    { type: "photo", id: "media-foto-9", align: "pos-left" },
    { type: "decoration", class: "fabric-ribbon", style: "bottom: 10px; right: 20px; transform: rotate(8deg);", text: "FOREVER" },
    { type: "section_end" },
    { type: "divider" },

    { type: "section_start", id: "sec-7" },
    { type: "title", text: "Untuk terakhir kalinya, hari ini" },
    { type: "paragraph", text: "Kalau kamu sudah sampai di bagian ini...." },
    { type: "paragraph", text: "Artinya kamu udah nemenin aku dari awal sampai akhir cerita kecil yang aku simpan di aplikasi ini.." },
    { type: "paragraph", text: "Terima kasih ya.." },
    { type: "paragraph", text: "Bukan cuma karena udah mau baca semuanya.." },
    { type: "paragraph", text: "Tapi juga karena udah hadir di hidup aku.." },
    { type: "paragraph", text: "Jujur, aku nggak tahu hubungan kita ke depannya bakal seperti apa. Aku juga nggak bisa janji kalau semuanya akan selalu berjalan mulus. Pasti akan ada salah paham, akan ada hari di mana kita sama-sama capek, sama-sama keras kepala, atau mungkin sama-sama kecewa.." },
    { type: "paragraph", text: "Tapi yang bisa aku janjiin adalah satu hal.." },
    { type: "paragraph", text: "Aku nggak mau berhenti berusaha.." },
    { type: "paragraph", text: "Aku akan terus belajar buat jadi laki-laki yang lebih baik. Belajar buat lebih ngerti kamu. Belajar buat lebih sabar. Belajar buat lebih banyak ngasih perhatian. Dan belajar buat menjaga apa yang sekarang kita punya.." },
    { type: "paragraph", text: "Aku tahu aku belum sempurna.." },
    { type: "paragraph", text: "Tapi percaya deh...." },
    { type: "paragraph", text: "Setiap hari aku selalu pengen jadi lebih baik dari hari sebelumnya. Bukan karena terpaksa, tapi karena aku pengen jadi seseorang yang memang pantas buat ada di samping kamu.." },
    { type: "paragraph", text: "Selamat ulang tahun yang ke-17 ya, Ciya.." },
    { type: "paragraph", text: "Semoga senyummu selalu jadi hal yang paling sering aku lihat.." },
    { type: "paragraph", text: "Aku sayang kamu.." },
    { type: "paragraph", text: "aku cinta kamu." },
    { type: "paragraph", text: "hari ini." },
    { type: "paragraph", text: "besok." },
    { type: "paragraph", text: "Dan semoga... untuk waktu yang sangat lama.." },
    { type: "photo", id: "media-foto-10", align: "pos-center", decor: "tape-washi" },
    { type: "decoration", class: "vintage-seal", text: "Special Day" },
    { type: "signature", closing: "Dengan penuh cinta,", name: "Ikhwan Faridz Bagaskara", date: "Jakarta, 06 Agustus 2026" },
    { type: "section_end" }
];
